version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
  account:
    container_name: account
    build:
      context: ${HUNCHO_DIR}/services/account
      dockerfile: ${HUNCHO_DIR}/services/account/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/account/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/account/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/account/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/account/seeds:/home/app/seeds
      - ${HUNCHO_DIR}/services/account/src:/home/app/src
      - ${HUNCHO_DIR}/services/account/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/account/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/account/setup.py:/home/app/setup.py
    env_file:
      - env/.env.account
    healthcheck:
      test: curl --fail -s account:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 20004:5000
    depends_on:
      - account_db
      - account_kafka
      - account_zookeeper
    networks:
      - app-net
  account_db:
    container_name: account_db
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.account_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U account" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
  account_kafka:
    container_name: account_kafka
    image: wurstmeister/kafka:latest
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/.env.account_kafka
    depends_on:
      - account_zookeeper
    networks:
      - app-net
  account_zookeeper:
    container_name: account_zookeeper
    image: wurstmeister/zookeeper:latest
    restart: on-failure
    env_file:
      - env/.env.account_zookeeper
    networks:
      - app-net
volumes:
  db_data:
networks:
  app-net:
    driver: bridge