"""empty message

Revision ID: 85a569e0e5a0
Revises: ca6a861ca70c
Create Date: 2020-08-18 23:42:32.831969

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '85a569e0e5a0'
down_revision = 'ca6a861ca70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['uuid'])
    op.create_unique_constraint(None, 'address', ['uuid'])
    op.add_column('membership', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False))
    op.add_column('membership', sa.Column('username', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'membership', ['email'])
    op.create_unique_constraint(None, 'membership', ['uuid'])
    op.create_unique_constraint(None, 'membership', ['username'])
    op.create_unique_constraint(None, 'phone', ['uuid'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_unique_constraint(None, 'status', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'phone', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_column('membership', 'username')
    op.drop_column('membership', 'email')
    op.drop_constraint(None, 'address', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
