"""empty message

Revision ID: 493aea13fac6
Revises: 4a02d9761683
Create Date: 2020-09-01 18:52:14.277327

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '493aea13fac6'
down_revision = '4a02d9761683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('ctime', sa.BigInteger(), nullable=True),
    sa.Column('mtime', sa.BigInteger(), nullable=True),
    sa.Column('s3_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('s3_filename', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('account', sa.Column('avatar_uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
    op.create_foreign_key(None, 'account', 'avatar', ['avatar_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'avatar_uuid')
    op.drop_table('avatar')
    # ### end Alembic commands ###
