"""empty message

Revision ID: 4a02d9761683
Revises: 89325b972756
Create Date: 2020-08-22 18:41:50.162523

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4a02d9761683'
down_revision = '89325b972756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['uuid'])
    op.create_unique_constraint(None, 'address', ['uuid'])
    op.create_unique_constraint(None, 'membership', ['uuid'])
    op.create_unique_constraint(None, 'phone', ['uuid'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_unique_constraint(None, 'status', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'phone', type_='unique')
    op.drop_constraint(None, 'membership', type_='unique')
    op.drop_constraint(None, 'address', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
