"""empty message

Revision ID: a5d26014a2f7
Revises: 493aea13fac6
Create Date: 2020-09-01 19:41:18.304028

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a5d26014a2f7'
down_revision = '493aea13fac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'avatar', ['uuid'])
    op.drop_column('avatar', 's3_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('s3_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'avatar', type_='unique')
    # ### end Alembic commands ###
